In [1]:
import numpy as np
import pandas as pd

In [4]:
a = [[1,2,3],[2,7,4]]
a_matrix = np.array(a)
print(a_matrix)

[[1 2 3]
 [2 7 4]]


In [5]:
b = [[1,-1],[0,1]]
b_matrix = np.array(b)
print(b_matrix)

[[ 1 -1]
 [ 0  1]]


In [6]:
c = [[5,-1],[9,1],[6,0]]
c_matrix = np.array(c)
print(c_matrix)

[[ 5 -1]
 [ 9  1]
 [ 6  0]]


In [7]:
d = [[3,-2,-1],[1,2,3]]
d_matrix = np.array(d)
print(d_matrix)

[[ 3 -2 -1]
 [ 1  2  3]]


In [8]:
u = [6,2,-3,5]
u_matrix = np.array(u)
print(u_matrix)

[ 6  2 -3  5]


In [9]:
v = [3,5,-1,4]
v_matrix = np.array(v)
print(v_matrix)

[ 3  5 -1  4]


In [10]:
w = [[1],[8],[0],[5]]
w_matrix = np.array(w)
print(w_matrix)

[[1]
 [8]
 [0]
 [5]]


1.1)

1. Matrix Dimensions

In [11]:
a_matrix.shape

(2, 3)

1.2)

In [12]:
b_matrix.shape

(2, 2)

1.3)

In [13]:
c_matrix.shape

(3, 2)

1.4)

In [14]:
d_matrix.shape

(2, 3)

1.5)

In [15]:
u_matrix.shape

(4,)

1.6)

2. Vector Operations

2.1)

In [17]:
u_matrix + v_matrix

array([ 9,  7, -4,  9])

2.2)

In [18]:
u_matrix - v_matrix

array([ 3, -3, -2,  1])

2.3)

In [21]:
6 * u_matrix

array([ 36,  12, -18,  30])

2.4)

In [22]:
u_matrix * v_matrix 

array([18, 10,  3, 20])

In [24]:
|u_matrix|

SyntaxError: invalid syntax (<ipython-input-24-1495d5f630d1>, line 1)

3. Matrix Operations

3.1)

In [25]:
a_matrix + c_matrix

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

3.2)

In [27]:
a_matrix - c_matrix.transpose()

array([[-4, -7, -3],
       [ 3,  6,  4]])

3.3)

In [28]:
c_matrix.transpose() + (3 * d_matrix)

array([[14,  3,  3],
       [ 2,  7,  9]])

3.4)

In [35]:
np.dot(b_matrix, a_matrix)

array([[-1, -5, -1],
       [ 2,  7,  4]])

3.5)

In [36]:
np.dot(b_matrix, a_matrix.transpose())

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

3.6)

In [37]:
np.dot(b_matrix, c_matrix)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

3.7)

In [38]:
np.dot(c_matrix, b_matrix)

array([[ 5, -6],
       [ 9, -8],
       [ 6, -6]])

3.8)

In [40]:
b_matrix^4

array([[ 5, -5],
       [ 4,  5]])

3.9)

In [41]:
np.dot(a_matrix, a_matrix.transpose())

array([[14, 28],
       [28, 69]])

3.10)

In [42]:
np.dot(d_matrix.transpose(), d_matrix)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])